version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgresdb
    environment:
      POSTGRES_DB: "usersdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1111"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - server-net
  dmt_webserver_backend:
    image: yuntys/dmt.webapi:latest
    container_name: webserverbackend
    environment:
      POSTGRES_HOST: postgresdb
    ports:
      - "6000:80"
    networks:
      - server-net
  dmt_agent_api:
    image: quteas/dmt-agent-api:latest  
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: webserveragentapi
    ports:
      - "8000:8000"
    networks:
      - server-net


networks:
  server-net: {}


volumes:
  db-data: